version: '3.8'
services:
  devenv:
    build:
      context: .
      args:
        - "DEVENV_USER=${DEVENV_USER}"
        - "DEVENV_PASS=${DEVENV_PASS}"
        - "DEVENV_EMAIL=${DEVENV_EMAIL}"
        - "DEVENV_LOCALE=${DEVENV_LOCALE}"
    container_name: devenv
    environment:
      - "DEVENV_USER=${DEVENV_USER}"
      - "DEVENV_PASS=${DEVENV_PASS}"
      - "DEVENV_EMAIL=${DEVENV_EMAIL}"
      - "DEVENV_LOCALE=${DEVENV_LOCALE}"
    volumes:
      - ${DEVENV_MOUNT_PATH}:/home/${DEVENV_USER}/host
      - config:/home/${DEVENV_USER}/.config:z
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  config:

