version: '3.9'
services:
  devenv:
    image: devenv
    container_name: devenv
    build:
      context: .
      dockerfile: base/Dockerfile
      args:
        - "DEVENV_USER=${DEVENV_USER}"
        - "DEVENV_PASS=${DEVENV_PASS}"
        - "DEVENV_EMAIL=${DEVENV_EMAIL}"
        - "DEVENV_LOCALE=${DEVENV_LOCALE}"
        - "DEVENV_MOUNT_PATH=${DEVENV_MOUNT_PATH}"
        - "DEVENV_GH_USER=${DEVENV_GH_USER}"
        - "DEVENV_GH_PASS=${DEVENV_GH_PASS}"
        - "DEVENV_SH_USER=${DEVENV_SH_USER}"
        - "DEVENV_SH_PASS=${DEVENV_SH_PASS}"
        - "PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/home/${DEVENV_USER}/perl5/bin"
    volumes:
      - ${DEVENV_MOUNT_PATH}:/home/${DEVENV_USER}/host
      - ./dotfiles:/home/${DEVENV_USER}/all_dotfiles
      - copilot:/home/${DEVENV_USER}/.config/github-copilot
    extra_hosts:
      - "host.docker.internal:host-gateway"
    user: "${DEVENV_USER}"
    ports:
      - 9003:9003
volumes:
  copilot:

